version: "3.9"  # optional since v1.27.0
services:
  db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_PASSWORD=12345
        - POSTGRES_USER=root
        - POSTGRES_DB=db
    ports:
        - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080